# Generated by Django 5.2 on 2025-05-07 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('give', 'Give Money'), ('borrow', 'Borrow Money'), ('spend', 'Spend Money'), ('receive', 'Receive Income'), ('remind', 'Set Reminder'), ('transfer', 'Transfer Money'), ('plan', 'Plan Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('target_person', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Action',
                'verbose_name_plural': 'Finance Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
