# Generated by Django 5.2 on 2025-05-07 13:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bosh_ustoz', models.FloatField(default=0, max_length=255)),
                ('Ustoz', models.FloatField(default=0, max_length=255)),
                ('Yordamchi_ustoz', models.FloatField(default=0, max_length=255)),
                ('Stajior', models.FloatField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('USER', 'Foydalanuvchi'), ('EMPLOYEE', 'Xodim')], default='USER', max_length=255, null=True)),
                ('degree', models.CharField(blank=True, choices=[('Oliy toifa', 'Oliy toifa'), ('Ikkinchi toifa', 'Ikkinchi toifa'), ('Yordamchi ustoz', 'Yordamchi ustoz'), ("Stajior o'qituvchi", "Stajior o'qituvchi")], max_length=255, null=True)),
                ('experience', models.CharField(blank=True, choices=[('1', '1 yil'), ('2', '2 yil'), ('3', '3 yil'), ('4', '4 yil'), ('5', '5 yil'), ('PROFESSIONAL', 'Professional')], default='1', max_length=255, null=True)),
                ('ball', models.CharField(blank=True, max_length=255, null=True)),
                ('bonus', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[("A'lo", "A'lo"), ('Yaxshi', 'Yaxshi'), ('Qoniqarli', 'Qoniqarli'), ('Qoniqarsiz', 'Qoniqarsiz')], max_length=255, null=True)),
                ('ball', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organized_date', models.DateField(blank=True, default=datetime.datetime(2025, 5, 7, 18, 20, 11, 745092), null=True)),
                ('type', models.CharField(blank=True, choices=[('Mock exam', 'Mock exam'), ('Tadbirlar', 'Tadbirlar'), ('Master klass', 'Master klass'), ('Trening', 'Trening'), ('Content Videolar', 'Content Videolar'), ('Guruh olib qolish', 'Guruh olib qolish')], max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'Tasdiqlandi'), ('IN_PROGRESS', 'Jarayonda'), ('REJECTED', 'Bekor qilindi')], default='IN_PROGRESS', max_length=255, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_even', to='bot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('GOETHE', 'Goethe'), ('MILLIY', 'Milliy'), ('TELC', 'Telc'), ('ÖSD', 'ÖSD'), ('Test_DAF', 'Test DAF'), ('prach_Diplom', 'Prache Diplom')], max_length=255, null=True)),
                ('degree', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=255, null=True)),
                ('files', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, choices=[('ME', 'Shaxsiy'), ('Student', "O'quvchimning")], default='ME', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'Tasdiqlandi'), ('IN_PROGRESS', 'Jarayonda'), ('REJECTED', 'Bekor qilindi')], default='IN_PROGRESS', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('INCOME', 'Bonus'), ('EXPENSE', 'Jarima')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_bonus', to='bot.user')),
            ],
        ),
    ]
