# Generated by Django 5.2 on 2025-05-07 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organized_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 5, 7, 18, 31, 16, 25602), null=True),
        ),
    ]
