# Generated by Django 5.2 on 2025-05-07 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_event_organized_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organized_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 5, 7, 18, 36, 48, 525882), null=True),
        ),
    ]
