# Generated by Django 5.2 on 2025-05-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_event_organized_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Kpi',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
